/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ultrasonic driver
 *
 * Author: Omar Muhammad
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_


#include "../MCAL/std_types.h"

#define ULTRASONIC_TRIGGER_PORT_ID PORTB_ID
#define ULTRASONIC_TRIGGER_PIN_ID PIN5_ID

#define ULTRASONIC_TRIGGER_PULSE_DURATION 10

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*1
 * Description :
 * Initialize the Ultrasonic:
 * 1. Setup the ICU call back function.
 * 2. Setup the direction for the trigger pin
 *     as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * 1. This is the call back function called by the ICU driver.
 * 2. Used to calculate the high time (pulse time) generated by
      the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
