/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Header file for the ultrasonic driver
 *
 * Author: Omar Muhammad
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "../MCAL/icu.h"
#include "../MCAL/gpio.h"
#include <util/delay.h>

static uint16 g_timeHigh = 0;

/*
 * Description :
 * Initialize the Ultrasonic:
 * 1. Initialize the ICU driver as required.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin
 *     as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/*Initialize the ICU driver as required.*/
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	Icu_init(&Icu_Config);

	/*Setting the call back function of ICU*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/*Setting the direction of the trigger pin as output pin through GPIO driver
	 * Writing zero on the trigger pin at the beginning*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);

}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);

	_delay_us(ULTRASONIC_TRIGGER_PULSE_DURATION);

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();

	/*Calculating the distance
	 * sound velocity:
	 * 					= 340 m/s = 34000 cm/s
	 *
	 * Distance of the object (in cm):
	 * 					= (speed * TIME)/2
	 * 					= 34000/2 * TIME
	 * 			    	= 17000 * TIME
	 * Note:
	 * Total distance is divided by 2 because signal travels from HC-SR04 to object and returns to the module HC-SR-04.
	 *
	 *  we have selected an internal 8MHz oscillator frequency for ATmega32, with Prescaler F_CPU/8 for timer frequency.
	 * Then time to execute 1 instruction is 1 us.So, the timer gets incremented after 1 us time elapse
	 * distance:
						= 17000 x (TIMER value) x 1 x 10^-6 cm
						= 0.017 x (TIMER value) cm
						= (TIMER value) / 58.8 cm or (TIMER value) * 0.017 cm
	 *
	 *
	 */

	return (g_timeHigh /58.8);
}

/*
 * Description :
 * 1. This is the call back function called by the ICU driver.
 * 2. Used to calculate the high time (pulse time) generated by
      the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	static uint16 g_edgeCount = 0;


	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount = 0;

	}
}
